version: '3.1'
services: 
  web:
    image: odoo:14.0
    ports: 
      - "8069:8069"
    volumes: 
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo 
      - ./addons:/mnt/extra-addons
    environment: 
      - HOST=db 
      - USER=odoo 
      - PASSWORD=myodoo 
    depends_on: 
      - db 
      - pgadmin 
  db:
    image: postgres:alpine
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=myodoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes: 
      - odoo-db-data:/var/lib/postgresql/data/pgdata
  pgadmin:
    image: dpage/pgadmin4:latest
    environment: 
      - PGADMIN_DEFAULT_EMAIL=mubethpraditya@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=mbohraroh1
      - PGADMIN_LISTEN_PORT=80
    volumes: 
      - pgadmin-data:/var/lib/pgadmin
    ports: 
      - "8080:80"
    depends_on: 
      - db 
volumes: 
  odoo-web-data:
  odoo-db-data:
  pgadmin-data: